import { appConfig } from "@/config/app";
import { DEFAULT_AVATAR_SRC } from "@/features/profile/constants";
import type { LocalProfile } from "@/features/profile/types";
import type { AuthSession, LocalAccount } from "@/features/auth/types";
import type { ReceivedCoupon } from "@/features/coupons/types/received-coupon";
import { TAXFREE_COUPONS_FALLBACK } from "@/features/coupons/data/taxfree-coupons";
import type { ShoppingItem } from "@/features/shopping-items/types";
import type { Scrap, Shot } from "@/features/shots/types";
import type { Trip } from "@/features/trips/types";
import {
  DEMO_ACCOUNT_CREDENTIALS,
  DEMO_DATA_VERSION,
  demoIds,
} from "./constants";

export const DEMO_SHOT_IMAGES = [
  "/demo/shots/haul-1.png",
  "/demo/shots/haul-2.png",
  "/demo/shots/haul-3.png",
  "/demo/shots/haul-4.png",
  "/demo/shots/haul-5.png",
] as const;

export const SHOT_DEMO_IMAGE_VERSION = 2;

export type DemoDataFixture = {
  trips: Trip[];
  items: ShoppingItem[];
  shots: Shot[];
  scraps: Scrap[];
  profile: LocalProfile;
  auth: AuthSession;
  accounts: LocalAccount[];
  receivedCoupons: ReceivedCoupon[];
  activeTripId: string;
  meta: Record<string, unknown>;
};

function koreaDay(reference: Date, offset: number) {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: "Asia/Seoul",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(reference);
  const values = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  const date = new Date(
    Date.UTC(
      Number(values.year),
      Number(values.month) - 1,
      Number(values.day) + offset,
    ),
  );
  return date.toISOString().slice(0, 10);
}

function hoursBefore(reference: Date, hours: number) {
  return new Date(reference.getTime() - hours * 3_600_000).toISOString();
}

function couponFixture(merchant: string, receivedAt: string): ReceivedCoupon {
  const coupon = TAXFREE_COUPONS_FALLBACK.find(
    (candidate) => candidate.merchant === merchant,
  );
  if (!coupon) throw new Error(`Missing demo coupon: ${merchant}`);
  return { ...coupon, receivedAt };
}

/**
 * Builds one internally consistent snapshot. IDs are stable; dates move relative
 * to the first installation day. The fixture deliberately keeps examples for
 * every home context at once so the trip switcher can preview idle, preparation,
 * in-trip, settlement, and older history without replacing the data set.
 */
export function buildDemoDataFixture(
  reference = new Date(),
): DemoDataFixture {
  const now = reference.toISOString();
  const profile: LocalProfile = {
    id: demoIds.profile,
    nickname: "여행자 해나",
    avatarDataUrl: DEFAULT_AVATAR_SRC,
    updatedAt: hoursBefore(reference, 3),
  };

  const trips: Trip[] = [
    {
      id: demoIds.trips.tokyo,
      name: "도쿄 골목 쇼핑",
      country: "일본",
      city: "도쿄",
      startDate: koreaDay(reference, -1),
      endDate: koreaDay(reference, 2),
      currency: "JPY",
      budget: 68000,
      createdAt: hoursBefore(reference, 24 * 24),
      updatedAt: hoursBefore(reference, 24 * 18),
    },
    {
      id: demoIds.trips.osaka,
      name: "오사카 맛집과 쇼핑",
      country: "일본",
      city: "오사카",
      startDate: koreaDay(reference, 24),
      endDate: koreaDay(reference, 27),
      currency: "JPY",
      budget: 85000,
      createdAt: hoursBefore(reference, 24 * 10),
      updatedAt: hoursBefore(reference, 8),
    },
    {
      id: demoIds.trips.taipei,
      name: "타이베이 간식 탐방",
      country: "대만",
      city: "타이베이",
      startDate: koreaDay(reference, -7),
      endDate: koreaDay(reference, -2),
      currency: "TWD",
      budget: 18000,
      createdAt: hoursBefore(reference, 24 * 70),
      updatedAt: hoursBefore(reference, 24 * 9),
    },
    {
      id: demoIds.trips.paris,
      name: "파리 마켓 산책",
      country: "프랑스",
      city: "파리",
      startDate: koreaDay(reference, -105),
      endDate: koreaDay(reference, -99),
      currency: "EUR",
      budget: 1200,
      createdAt: hoursBefore(reference, 24 * 150),
      updatedAt: hoursBefore(reference, 24 * 98),
    },
    {
      id: demoIds.trips.fukuoka,
      name: "후쿠오카 주말 쇼핑",
      country: "일본",
      city: "후쿠오카",
      startDate: koreaDay(reference, 5),
      endDate: koreaDay(reference, 8),
      currency: "JPY",
      budget: 72000,
      createdAt: hoursBefore(reference, 24 * 14),
      updatedAt: hoursBefore(reference, 5),
    },
    // 지난 여행 4건. 기존 타이베이·파리 기록과 합쳐 여권을 두 펼침
    // 이상으로 만들고, 국가별 도장과 여러 통화 표기를 함께 확인한다.
    {
      id: demoIds.trips.kyoto,
      name: "교토 공예품 산책",
      country: "일본",
      city: "교토",
      startDate: koreaDay(reference, -14),
      endDate: koreaDay(reference, -10),
      currency: "JPY",
      budget: 56000,
      createdAt: hoursBefore(reference, 24 * 52),
      updatedAt: hoursBefore(reference, 24 * 10),
    },
    {
      id: demoIds.trips.seoul,
      name: "서울 성수 소품 나들이",
      country: "한국",
      city: "서울",
      startDate: koreaDay(reference, -45),
      endDate: koreaDay(reference, -43),
      currency: "KRW",
      budget: 300000,
      createdAt: hoursBefore(reference, 24 * 62),
      updatedAt: hoursBefore(reference, 24 * 43),
    },
    {
      id: demoIds.trips.bangkok,
      name: "방콕 야시장 털기",
      country: "태국",
      city: "방콕",
      startDate: koreaDay(reference, -160),
      endDate: koreaDay(reference, -155),
      currency: "THB",
      budget: 14000,
      createdAt: hoursBefore(reference, 24 * 190),
      updatedAt: hoursBefore(reference, 24 * 155),
    },
    {
      id: demoIds.trips.rome,
      name: "로마 식료품 순례",
      country: "이탈리아",
      city: "로마",
      startDate: koreaDay(reference, -230),
      endDate: koreaDay(reference, -224),
      currency: "EUR",
      budget: 900,
      createdAt: hoursBefore(reference, 24 * 268),
      updatedAt: hoursBefore(reference, 24 * 224),
    },
  ];

  const items: ShoppingItem[] = [
    {
      id: demoIds.items.tokyoSunscreen,
      tripId: demoIds.trips.tokyo,
      name: "아넷사 선크림",
      estimatedPrice: 2480,
      quantity: 2,
      memo: "마츠키요 쿠폰 확인",
      imageDataUrl: "/shopping/mag-drugstore-checklist.png",
      plannedPurchaseDate: koreaDay(reference, 0),
      giftTags: ["friend"],
      purchased: false,
      purchasedAt: null,
      sortOrder: 101,
      createdAt: hoursBefore(reference, 24 * 28),
      updatedAt: hoursBefore(reference, 4),
    },
    {
      id: demoIds.items.tokyoCoffee,
      tripId: demoIds.trips.tokyo,
      name: "드립백 커피 세트",
      estimatedPrice: 1680,
      quantity: 3,
      memo: "회사 선물",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, 0),
      giftTags: ["colleague"],
      purchased: false,
      purchasedAt: null,
      sortOrder: 102,
      createdAt: hoursBefore(reference, 24 * 27),
      updatedAt: hoursBefore(reference, 3),
    },
    {
      id: demoIds.items.tokyoStationery,
      tripId: demoIds.trips.tokyo,
      name: "트래블러스 노트 리필",
      estimatedPrice: 990,
      quantity: 2,
      memo: "나카메구로 한정 색상 확인",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, 1),
      giftTags: [],
      purchased: false,
      purchasedAt: null,
      sortOrder: 103,
      createdAt: hoursBefore(reference, 24 * 26),
      updatedAt: hoursBefore(reference, 2),
    },
    {
      id: demoIds.items.tokyoCamera,
      tripId: demoIds.trips.tokyo,
      name: "일회용 필름 카메라",
      estimatedPrice: 2180,
      quantity: 1,
      memo: "빅카메라 재고 보기",
      imageDataUrl: "/shopping/mall-bic-akihabara.png",
      plannedPurchaseDate: koreaDay(reference, -1),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 22),
      sortOrder: 104,
      createdAt: hoursBefore(reference, 24 * 27),
      updatedAt: hoursBefore(reference, 22),
    },
    {
      id: demoIds.items.tokyoSnacks,
      tripId: demoIds.trips.tokyo,
      name: "지역 한정 과자 모음",
      estimatedPrice: 1350,
      quantity: 4,
      memo: "낱개 포장 제품",
      imageDataUrl: "/shopping/mall-donki-shibuya.png",
      plannedPurchaseDate: koreaDay(reference, 0),
      giftTags: ["acquaintance", "colleague"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 2),
      sortOrder: 105,
      createdAt: hoursBefore(reference, 24 * 26),
      updatedAt: hoursBefore(reference, 2),
    },
    {
      id: demoIds.items.tokyoHandCream,
      tripId: demoIds.trips.tokyo,
      name: "유자 핸드크림",
      estimatedPrice: 880,
      quantity: 2,
      memo: "향 테스트 후 구매",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, 2),
      giftTags: ["friend"],
      purchased: false,
      purchasedAt: null,
      sortOrder: 106,
      createdAt: hoursBefore(reference, 24 * 25),
      updatedAt: hoursBefore(reference, 1),
    },
    {
      id: demoIds.items.osakaKitkat,
      tripId: demoIds.trips.osaka,
      name: "간사이 한정 키트캣",
      estimatedPrice: 1580,
      quantity: 3,
      memo: "귀국 전 돈키호테",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, 26),
      giftTags: ["acquaintance"],
      purchased: false,
      purchasedAt: null,
      sortOrder: 201,
      createdAt: hoursBefore(reference, 24 * 6),
      updatedAt: hoursBefore(reference, 8),
    },
    {
      id: demoIds.items.osakaPatches,
      tripId: demoIds.trips.osaka,
      name: "로이히츠보 파스",
      estimatedPrice: 980,
      quantity: 2,
      memo: "가족 부탁",
      imageDataUrl: "/shopping/mag-drugstore-checklist.png",
      plannedPurchaseDate: koreaDay(reference, 25),
      giftTags: ["friend"],
      purchased: false,
      purchasedAt: null,
      sortOrder: 202,
      createdAt: hoursBefore(reference, 24 * 5),
      updatedAt: hoursBefore(reference, 24),
    },
    {
      id: demoIds.items.osakaTowel,
      tripId: demoIds.trips.osaka,
      name: "캐릭터 미니 타월",
      estimatedPrice: 770,
      quantity: 4,
      memo: "색상 다르게",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, 24),
      giftTags: ["colleague"],
      purchased: false,
      purchasedAt: null,
      sortOrder: 203,
      createdAt: hoursBefore(reference, 24 * 4),
      updatedAt: hoursBefore(reference, 24),
    },
    {
      id: demoIds.items.osakaTea,
      tripId: demoIds.trips.osaka,
      name: "호지차 티백",
      estimatedPrice: 1200,
      quantity: 2,
      memo: "쿠로몬 시장",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, 25),
      giftTags: [],
      purchased: false,
      purchasedAt: null,
      sortOrder: 204,
      createdAt: hoursBefore(reference, 24 * 3),
      updatedAt: hoursBefore(reference, 8),
    },
    {
      id: demoIds.items.osakaMascot,
      tripId: demoIds.trips.osaka,
      name: "오사카 한정 마스코트",
      estimatedPrice: 1980,
      quantity: 1,
      memo: "현장에서 디자인 고르기",
      imageDataUrl: null,
      plannedPurchaseDate: null,
      giftTags: [],
      purchased: false,
      purchasedAt: null,
      sortOrder: 205,
      createdAt: hoursBefore(reference, 24 * 2),
      updatedAt: hoursBefore(reference, 7),
    },
    {
      id: demoIds.items.taipeiPineappleCake,
      tripId: demoIds.trips.taipei,
      name: "펑리수 12개입",
      estimatedPrice: 480,
      quantity: 3,
      memo: "디화제 매장",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -6),
      giftTags: ["acquaintance", "colleague"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 6),
      sortOrder: 301,
      createdAt: hoursBefore(reference, 24 * 60),
      updatedAt: hoursBefore(reference, 24 * 6),
    },
    {
      id: demoIds.items.taipeiTea,
      tripId: demoIds.trips.taipei,
      name: "동방미인 우롱차",
      estimatedPrice: 620,
      quantity: 2,
      memo: "시음한 제품으로",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -5),
      giftTags: ["friend"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 5),
      sortOrder: 302,
      createdAt: hoursBefore(reference, 24 * 58),
      updatedAt: hoursBefore(reference, 24 * 5),
    },
    {
      id: demoIds.items.taipeiToothpaste,
      tripId: demoIds.trips.taipei,
      name: "다리 치약",
      estimatedPrice: 180,
      quantity: 4,
      memo: "까르푸",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -3),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 3),
      sortOrder: 303,
      createdAt: hoursBefore(reference, 24 * 55),
      updatedAt: hoursBefore(reference, 24 * 3),
    },
    {
      id: demoIds.items.taipeiNougat,
      tripId: demoIds.trips.taipei,
      name: "누가 크래커",
      estimatedPrice: 360,
      quantity: 5,
      memo: "개별 포장 확인",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -4),
      giftTags: ["colleague"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 4),
      sortOrder: 304,
      createdAt: hoursBefore(reference, 24 * 54),
      updatedAt: hoursBefore(reference, 24 * 4),
    },
    {
      id: demoIds.items.taipeiBag,
      tripId: demoIds.trips.taipei,
      name: "자수 미니 가방",
      estimatedPrice: 890,
      quantity: 1,
      memo: "중산역 편집숍",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -2),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 2),
      sortOrder: 305,
      createdAt: hoursBefore(reference, 24 * 52),
      updatedAt: hoursBefore(reference, 24 * 2),
    },
    {
      id: demoIds.items.parisSoap,
      tripId: demoIds.trips.paris,
      name: "마르세유 비누",
      estimatedPrice: 8,
      quantity: 5,
      memo: "시장 기념품",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -102),
      giftTags: ["acquaintance"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 102),
      sortOrder: 401,
      createdAt: hoursBefore(reference, 24 * 140),
      updatedAt: hoursBefore(reference, 24 * 102),
    },
    {
      id: demoIds.items.parisTea,
      tripId: demoIds.trips.paris,
      name: "홍차 틴 케이스",
      estimatedPrice: 24,
      quantity: 2,
      memo: "선물 포장 요청",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -101),
      giftTags: ["friend"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 101),
      sortOrder: 402,
      createdAt: hoursBefore(reference, 24 * 138),
      updatedAt: hoursBefore(reference, 24 * 101),
    },
    {
      id: demoIds.items.parisJam,
      tripId: demoIds.trips.paris,
      name: "무화과 콩피튀르",
      estimatedPrice: 12,
      quantity: 2,
      memo: "유리병 완충 포장",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -104),
      giftTags: ["friend"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 104),
      sortOrder: 403,
      createdAt: hoursBefore(reference, 24 * 139),
      updatedAt: hoursBefore(reference, 24 * 104),
    },
    {
      id: demoIds.items.parisNotebook,
      tripId: demoIds.trips.paris,
      name: "마레 지구 노트",
      estimatedPrice: 15,
      quantity: 3,
      memo: "표지 무늬 다르게",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -103),
      giftTags: ["colleague"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 103),
      sortOrder: 404,
      createdAt: hoursBefore(reference, 24 * 137),
      updatedAt: hoursBefore(reference, 24 * 103),
    },
    {
      id: demoIds.items.parisSalt,
      tripId: demoIds.trips.paris,
      name: "게랑드 소금",
      estimatedPrice: 7,
      quantity: 2,
      memo: "굵은 입자 제품",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -100),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 100),
      sortOrder: 405,
      createdAt: hoursBefore(reference, 24 * 136),
      updatedAt: hoursBefore(reference, 24 * 100),
    },
    {
      id: demoIds.items.fukuokaMentaiko,
      tripId: demoIds.trips.fukuoka,
      name: "명란 센베이",
      estimatedPrice: 1450,
      quantity: 3,
      memo: "하카타역에서 가격 비교",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, 5),
      giftTags: ["colleague"],
      purchased: false,
      purchasedAt: null,
      sortOrder: 501,
      createdAt: hoursBefore(reference, 24 * 8),
      updatedAt: hoursBefore(reference, 5),
    },
    {
      id: demoIds.items.fukuokaStrawberry,
      tripId: demoIds.trips.fukuoka,
      name: "아마오우 딸기 과자",
      estimatedPrice: 1280,
      quantity: 4,
      memo: "개별 포장 확인",
      imageDataUrl: "/shopping/mall-donki-shibuya.png",
      plannedPurchaseDate: koreaDay(reference, 6),
      giftTags: ["acquaintance"],
      purchased: false,
      purchasedAt: null,
      sortOrder: 502,
      createdAt: hoursBefore(reference, 24 * 7),
      updatedAt: hoursBefore(reference, 6),
    },
    {
      id: demoIds.items.fukuokaRamen,
      tripId: demoIds.trips.fukuoka,
      name: "돈코츠 라멘 세트",
      estimatedPrice: 1980,
      quantity: 2,
      memo: "수하물 무게 확인",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, 6),
      giftTags: ["friend"],
      purchased: false,
      purchasedAt: null,
      sortOrder: 503,
      createdAt: hoursBefore(reference, 24 * 6),
      updatedAt: hoursBefore(reference, 4),
    },
    {
      id: demoIds.items.fukuokaPouch,
      tripId: demoIds.trips.fukuoka,
      name: "하카타오리 파우치",
      estimatedPrice: 3200,
      quantity: 1,
      memo: "차분한 남색으로",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, 7),
      giftTags: [],
      purchased: false,
      purchasedAt: null,
      sortOrder: 504,
      createdAt: hoursBefore(reference, 24 * 5),
      updatedAt: hoursBefore(reference, 3),
    },
    {
      id: demoIds.items.fukuokaTea,
      tripId: demoIds.trips.fukuoka,
      name: "야메차 티백",
      estimatedPrice: 1100,
      quantity: 2,
      memo: "현지에서 시음 후 결정",
      imageDataUrl: null,
      plannedPurchaseDate: null,
      giftTags: [],
      purchased: false,
      purchasedAt: null,
      sortOrder: 505,
      createdAt: hoursBefore(reference, 24 * 4),
      updatedAt: hoursBefore(reference, 2),
    },
    {
      id: demoIds.items.kyotoIncense,
      tripId: demoIds.trips.kyoto,
      name: "교토 향 인센스 세트",
      estimatedPrice: 2800,
      quantity: 2,
      memo: "백단향과 벚꽃향으로 구매",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -14),
      giftTags: ["friend"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 14),
      sortOrder: 601,
      createdAt: hoursBefore(reference, 24 * 48),
      updatedAt: hoursBefore(reference, 24 * 14),
    },
    {
      id: demoIds.items.kyotoFuroshiki,
      tripId: demoIds.trips.kyoto,
      name: "전통 후로시키 보자기",
      estimatedPrice: 2200,
      quantity: 3,
      memo: "선물 포장용으로 무늬 다르게",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -13),
      giftTags: ["acquaintance"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 13),
      sortOrder: 602,
      createdAt: hoursBefore(reference, 24 * 47),
      updatedAt: hoursBefore(reference, 24 * 13),
    },
    {
      id: demoIds.items.kyotoMatcha,
      tripId: demoIds.trips.kyoto,
      name: "우지 말차 틴",
      estimatedPrice: 3600,
      quantity: 2,
      memo: "제과용이 아닌 음용 등급",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -12),
      giftTags: ["colleague"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 12),
      sortOrder: 603,
      createdAt: hoursBefore(reference, 24 * 46),
      updatedAt: hoursBefore(reference, 24 * 12),
    },
    {
      id: demoIds.items.kyotoTenugui,
      tripId: demoIds.trips.kyoto,
      name: "계절 무늬 테누구이",
      estimatedPrice: 1500,
      quantity: 2,
      memo: "여권 노트 커버로 활용",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -11),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 11),
      sortOrder: 604,
      createdAt: hoursBefore(reference, 24 * 45),
      updatedAt: hoursBefore(reference, 24 * 11),
    },
    {
      id: demoIds.items.kyotoCeramics,
      tripId: demoIds.trips.kyoto,
      name: "기요미즈야키 찻잔",
      estimatedPrice: 6800,
      quantity: 1,
      memo: "수하물용 완충 포장 요청",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -10),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 10),
      sortOrder: 605,
      createdAt: hoursBefore(reference, 24 * 44),
      updatedAt: hoursBefore(reference, 24 * 10),
    },
    {
      id: demoIds.items.seoulCandle,
      tripId: demoIds.trips.seoul,
      name: "성수동 수제 향초",
      estimatedPrice: 28000,
      quantity: 2,
      memo: "무화과 향으로 골랐음",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -45),
      giftTags: ["acquaintance"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 45),
      sortOrder: 701,
      createdAt: hoursBefore(reference, 24 * 60),
      updatedAt: hoursBefore(reference, 24 * 45),
    },
    {
      id: demoIds.items.seoulTray,
      tripId: demoIds.trips.seoul,
      name: "광장시장 자개 트레이",
      estimatedPrice: 45000,
      quantity: 1,
      memo: "흠집 확인하고 구매",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -44),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 44),
      sortOrder: 702,
      createdAt: hoursBefore(reference, 24 * 59),
      updatedAt: hoursBefore(reference, 24 * 44),
    },
    {
      id: demoIds.items.seoulYakgwa,
      tripId: demoIds.trips.seoul,
      name: "약과 선물세트",
      estimatedPrice: 22000,
      quantity: 3,
      memo: "사무실 나눠 먹을 용도",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -44),
      giftTags: ["colleague"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 44),
      sortOrder: 703,
      createdAt: hoursBefore(reference, 24 * 58),
      updatedAt: hoursBefore(reference, 24 * 44),
    },
    {
      id: demoIds.items.seoulBeans,
      tripId: demoIds.trips.seoul,
      name: "한남동 로스터리 원두",
      estimatedPrice: 19000,
      quantity: 2,
      memo: "분쇄하지 않고 홀빈으로",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -43),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 43),
      sortOrder: 704,
      createdAt: hoursBefore(reference, 24 * 57),
      updatedAt: hoursBefore(reference, 24 * 43),
    },
    {
      id: demoIds.items.seoulTeacup,
      tripId: demoIds.trips.seoul,
      name: "인사동 전통 찻잔",
      estimatedPrice: 36000,
      quantity: 1,
      memo: "포장 꼼꼼히 요청",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -43),
      giftTags: ["friend"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 43),
      sortOrder: 705,
      createdAt: hoursBefore(reference, 24 * 56),
      updatedAt: hoursBefore(reference, 24 * 43),
    },
    {
      id: demoIds.items.bangkokCoconutOil,
      tripId: demoIds.trips.bangkok,
      name: "코코넛 오일",
      estimatedPrice: 320,
      quantity: 4,
      memo: "대용량이 더 저렴",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -159),
      giftTags: ["acquaintance"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 159),
      sortOrder: 801,
      createdAt: hoursBefore(reference, 24 * 185),
      updatedAt: hoursBefore(reference, 24 * 159),
    },
    {
      id: demoIds.items.bangkokRattanBag,
      tripId: demoIds.trips.bangkok,
      name: "짜뚜짝 라탄 가방",
      estimatedPrice: 850,
      quantity: 1,
      memo: "흥정해서 구매",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -158),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 158),
      sortOrder: 802,
      createdAt: hoursBefore(reference, 24 * 184),
      updatedAt: hoursBefore(reference, 24 * 158),
    },
    {
      id: demoIds.items.bangkokSilkScarf,
      tripId: demoIds.trips.bangkok,
      name: "타이 실크 스카프",
      estimatedPrice: 1200,
      quantity: 2,
      memo: "짙은 색 위주로",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -157),
      giftTags: ["friend"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 157),
      sortOrder: 803,
      createdAt: hoursBefore(reference, 24 * 183),
      updatedAt: hoursBefore(reference, 24 * 157),
    },
    {
      id: demoIds.items.bangkokHerbBalm,
      tripId: demoIds.trips.bangkok,
      name: "허브 흡입제 (야돔)",
      estimatedPrice: 90,
      quantity: 10,
      memo: "사무실 인원수대로",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -156),
      giftTags: ["colleague"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 156),
      sortOrder: 804,
      createdAt: hoursBefore(reference, 24 * 182),
      updatedAt: hoursBefore(reference, 24 * 156),
    },
    {
      id: demoIds.items.bangkokMangoJelly,
      tripId: demoIds.trips.bangkok,
      name: "망고 젤리",
      estimatedPrice: 150,
      quantity: 6,
      memo: "공항 면세점이 더 쌌음",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -155),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 155),
      sortOrder: 805,
      createdAt: hoursBefore(reference, 24 * 181),
      updatedAt: hoursBefore(reference, 24 * 155),
    },
    {
      id: demoIds.items.romeTruffleOil,
      tripId: demoIds.trips.rome,
      name: "트러플 오일",
      estimatedPrice: 18,
      quantity: 2,
      memo: "기내 반입 불가, 수하물로",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -229),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 229),
      sortOrder: 901,
      createdAt: hoursBefore(reference, 24 * 260),
      updatedAt: hoursBefore(reference, 24 * 229),
    },
    {
      id: demoIds.items.romeParmigiano,
      tripId: demoIds.trips.rome,
      name: "파르미지아노 레지아노",
      estimatedPrice: 32,
      quantity: 1,
      memo: "진공 포장 요청",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -228),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 228),
      sortOrder: 902,
      createdAt: hoursBefore(reference, 24 * 259),
      updatedAt: hoursBefore(reference, 24 * 228),
    },
    {
      id: demoIds.items.romeSoap,
      tripId: demoIds.trips.rome,
      name: "산타 마리아 노벨라 비누",
      estimatedPrice: 14,
      quantity: 4,
      memo: "향 종류별로 하나씩",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -227),
      giftTags: ["acquaintance"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 227),
      sortOrder: 903,
      createdAt: hoursBefore(reference, 24 * 258),
      updatedAt: hoursBefore(reference, 24 * 227),
    },
    {
      id: demoIds.items.romeCardWallet,
      tripId: demoIds.trips.rome,
      name: "가죽 카드지갑",
      estimatedPrice: 45,
      quantity: 1,
      memo: "이니셜 각인 서비스 포함",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -226),
      giftTags: ["friend"],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 226),
      sortOrder: 904,
      createdAt: hoursBefore(reference, 24 * 257),
      updatedAt: hoursBefore(reference, 24 * 226),
    },
    {
      id: demoIds.items.romeMokaPot,
      tripId: demoIds.trips.rome,
      name: "에스프레소 모카포트",
      estimatedPrice: 38,
      quantity: 1,
      memo: "3인용 크기로",
      imageDataUrl: null,
      plannedPurchaseDate: koreaDay(reference, -225),
      giftTags: [],
      purchased: true,
      purchasedAt: hoursBefore(reference, 24 * 225),
      sortOrder: 905,
      createdAt: hoursBefore(reference, 24 * 256),
      updatedAt: hoursBefore(reference, 24 * 225),
    },
  ];

  const shots: Shot[] = [
    {
      id: demoIds.shots.ownTokyo,
      channel: "shots",
      tripId: demoIds.trips.tokyo,
      authorId: profile.id,
      authorNickname: profile.nickname,
      authorAvatarDataUrl: profile.avatarDataUrl,
      destinationCountry: "일본",
      destinationCity: "도쿄",
      images: [DEMO_SHOT_IMAGES[3], DEMO_SHOT_IMAGES[1]],
      pins: [
        {
          id: "demo-v1-pin-own-tokyo-1",
          imageIndex: 0,
          xPct: 61,
          yPct: 38,
          text: "시부야에서 산 한정 과자",
        },
      ],
      body: "도쿄 첫날 쇼핑 기록. 필요한 것만 체크하면서 담으니 캐리어가 아직 여유로워요.",
      shoppingItemIds: [
        demoIds.items.tokyoCamera,
        demoIds.items.tokyoSnacks,
      ],
      likeCount: 18,
      likedByMe: false,
      shareCount: 2,
      comments: [
        {
          id: "demo-v1-comment-own-tokyo-1",
          authorId: "demo-author-mina",
          authorNickname: "미나의여행",
          text: "과자 패키지가 정말 귀여워요!",
          createdAt: hoursBefore(reference, 7),
        },
      ],
      createdAt: hoursBefore(reference, 12),
      updatedAt: hoursBefore(reference, 7),
    },
    {
      id: demoIds.shots.ownTaipei,
      channel: "shots",
      tripId: demoIds.trips.taipei,
      authorId: profile.id,
      authorNickname: profile.nickname,
      authorAvatarDataUrl: profile.avatarDataUrl,
      destinationCountry: "대만",
      destinationCity: "타이베이",
      images: [DEMO_SHOT_IMAGES[4]],
      pins: [],
      body: "타이베이에서 사 온 간식과 차. 선물별로 나눠 두니 정리하기 편했어요.",
      shoppingItemIds: [
        demoIds.items.taipeiPineappleCake,
        demoIds.items.taipeiTea,
      ],
      likeCount: 31,
      likedByMe: false,
      shareCount: 5,
      comments: [],
      createdAt: hoursBefore(reference, 16),
      updatedAt: hoursBefore(reference, 16),
    },
    {
      id: demoIds.shots.osakaHaul,
      channel: "shots",
      tripId: demoIds.trips.osaka,
      authorId: "demo-author-cream",
      authorNickname: "크림밤빵",
      authorAvatarDataUrl: null,
      destinationCountry: "일본",
      destinationCity: "오사카",
      images: [
        DEMO_SHOT_IMAGES[0],
        DEMO_SHOT_IMAGES[2],
        DEMO_SHOT_IMAGES[1],
      ],
      pins: [
        {
          id: "demo-v1-pin-osaka-1",
          imageIndex: 0,
          xPct: 34,
          yPct: 43,
          text: "난바 드럭스토어에서 발견",
        },
        {
          id: "demo-v1-pin-osaka-2",
          imageIndex: 2,
          xPct: 88,
          yPct: 18,
          text: "마지막 장의 호지차도 추천",
        },
      ],
      body: "오사카 쇼핑 동선 공유해요. 파스와 간식은 난바에서 한 번에 사기 좋았어요.",
      shoppingItemIds: [
        demoIds.items.osakaKitkat,
        demoIds.items.osakaPatches,
      ],
      likeCount: 142,
      likedByMe: true,
      shareCount: 28,
      comments: [
        {
          id: "demo-v1-comment-osaka-1",
          authorId: profile.id,
          authorNickname: profile.nickname,
          text: "다음 여행 리스트에 참고할게요.",
          createdAt: hoursBefore(reference, 30),
        },
        {
          id: "demo-v1-comment-osaka-2",
          authorId: "demo-author-yuri",
          authorNickname: "유리창가",
          text: "난바 동선 정보 고마워요!",
          createdAt: hoursBefore(reference, 28),
        },
        {
          id: "demo-v1-comment-osaka-3",
          authorId: "demo-author-haru",
          authorNickname: "하루한걸음",
          text: "사진 핀 덕분에 제품 찾기 쉽겠어요.",
          createdAt: hoursBefore(reference, 27),
        },
      ],
      createdAt: hoursBefore(reference, 42),
      updatedAt: hoursBefore(reference, 27),
    },
    {
      id: demoIds.shots.tokyoDrugstore,
      channel: "shots",
      tripId: demoIds.trips.tokyo,
      authorId: "demo-author-momo",
      authorNickname: "모모산책",
      authorAvatarDataUrl: null,
      destinationCountry: "일본",
      destinationCity: "도쿄",
      images: [DEMO_SHOT_IMAGES[2]],
      pins: [
        {
          id: "demo-v1-pin-tokyo-drugstore-1",
          imageIndex: 0,
          xPct: 52,
          yPct: 59,
          text: "선크림은 매장별 가격 비교",
        },
      ],
      body: "신주쿠 드럭스토어 세 곳을 돌아본 기록이에요. 쿠폰 조건은 계산 전에 다시 확인했어요.",
      shoppingItemIds: [demoIds.items.tokyoSunscreen],
      likeCount: 96,
      likedByMe: true,
      shareCount: 14,
      comments: [],
      createdAt: hoursBefore(reference, 55),
      updatedAt: hoursBefore(reference, 55),
    },
    {
      id: demoIds.shots.taipeiSnacks,
      channel: "shots",
      tripId: demoIds.trips.taipei,
      authorId: "demo-author-niu",
      authorNickname: "니우의간식장",
      authorAvatarDataUrl: null,
      destinationCountry: "대만",
      destinationCity: "타이베이",
      images: [DEMO_SHOT_IMAGES[4], DEMO_SHOT_IMAGES[0]],
      pins: [],
      body: "디화제와 시먼딩에서 산 간식 모음. 펑리수는 여러 집을 조금씩 비교했어요.",
      shoppingItemIds: [
        demoIds.items.taipeiPineappleCake,
        demoIds.items.taipeiToothpaste,
      ],
      likeCount: 74,
      likedByMe: false,
      shareCount: 19,
      comments: [],
      createdAt: hoursBefore(reference, 30),
      updatedAt: hoursBefore(reference, 30),
    },
    {
      id: demoIds.shots.parisMarket,
      channel: "shots",
      tripId: demoIds.trips.paris,
      authorId: "demo-author-lea",
      authorNickname: "레아마켓",
      authorAvatarDataUrl: null,
      destinationCountry: "프랑스",
      destinationCity: "파리",
      images: [DEMO_SHOT_IMAGES[1]],
      pins: [],
      body: "파리 마켓에서 고른 작은 선물들. 무게가 가벼운 비누와 틴 케이스 위주로 담았어요.",
      shoppingItemIds: [demoIds.items.parisSoap, demoIds.items.parisTea],
      likeCount: 53,
      likedByMe: true,
      shareCount: 9,
      comments: [],
      createdAt: hoursBefore(reference, 24 * 65),
      updatedAt: hoursBefore(reference, 24 * 65),
    },
    {
      id: demoIds.shots.tokyoCommunity,
      channel: "community",
      tripId: demoIds.trips.tokyo,
      authorId: "demo-author-sora",
      authorNickname: "소라빛여행",
      authorAvatarDataUrl: null,
      destinationCountry: "일본",
      destinationCity: "도쿄",
      images: [DEMO_SHOT_IMAGES[3]],
      pins: [],
      body: "비 오는 날 긴자에서 둘러본 실내 쇼핑 동선. 문구점과 지하상가를 이어 걸었어요.",
      shoppingItemIds: [],
      likeCount: 22,
      likedByMe: false,
      shareCount: 1,
      comments: [
        {
          id: "demo-v1-comment-community-tokyo-1",
          authorId: profile.id,
          authorNickname: profile.nickname,
          text: "긴자 이토야부터 시작하면 이동이 짧았어요.",
          createdAt: hoursBefore(reference, 4),
        },
      ],
      createdAt: hoursBefore(reference, 6),
      updatedAt: hoursBefore(reference, 4),
    },
    {
      id: demoIds.shots.osakaCommunity,
      channel: "community",
      tripId: demoIds.trips.osaka,
      authorId: "demo-author-jun",
      authorNickname: "준의주말",
      authorAvatarDataUrl: null,
      destinationCountry: "일본",
      destinationCity: "오사카",
      images: [DEMO_SHOT_IMAGES[0]],
      pins: [],
      body: "우메다에서 난바까지 하루 쇼핑 동선을 정리했어요. 오전에는 북쪽, 저녁에는 도톤보리 순서가 편했어요.",
      shoppingItemIds: [],
      likeCount: 12,
      likedByMe: false,
      shareCount: 0,
      comments: [],
      createdAt: hoursBefore(reference, 26),
      updatedAt: hoursBefore(reference, 26),
    },
  ];

  const scraps: Scrap[] = [
    {
      id: demoIds.scraps.osakaHaul,
      shotId: demoIds.shots.osakaHaul,
      createdAt: hoursBefore(reference, 10),
    },
    {
      id: demoIds.scraps.taipeiSnacks,
      shotId: demoIds.shots.taipeiSnacks,
      createdAt: hoursBefore(reference, 24 * 3),
    },
    {
      id: demoIds.scraps.parisMarket,
      shotId: demoIds.shots.parisMarket,
      createdAt: hoursBefore(reference, 24 * 8),
    },
  ];

  return {
    trips,
    items,
    shots,
    scraps,
    profile,
    auth: {
      isLoggedIn: true,
      loggedInAt: hoursBefore(reference, 3),
      provider: "email",
      email: demoIds.accountEmail,
    },
    accounts: [
      {
        email: demoIds.accountEmail,
        // SHA-256 for the replaceable local-only fixture password.
        passwordHash: DEMO_ACCOUNT_CREDENTIALS.passwordHash,
        nickname: profile.nickname,
        createdAt: hoursBefore(reference, 24 * 30),
      },
    ],
    receivedCoupons: [
      couponFixture("돈키호테", hoursBefore(reference, 9)),
      couponFixture("빅카메라", hoursBefore(reference, 24 * 2)),
      couponFixture("마츠모토키요시", hoursBefore(reference, 24 * 5)),
    ],
    // The cold-start preview opens on the ordinary home while keeping live,
    // prep, and settlement trips in the same fixture for immediate switching.
    activeTripId: demoIds.trips.osaka,
    meta: {
      version: appConfig.storageVersion,
      seededAt: now,
      demoDataVersion: DEMO_DATA_VERSION,
      shotDemoImageVersion: SHOT_DEMO_IMAGE_VERSION,
    },
  };
}
